blueprint:
  name: Octopus Energy - Join Saving Session
  description: Automatically joins saving sessions when they become available
  domain: automation
  author: BottlecapDave
  input:
    saving_session_event_entity:
      name: Saving session events
      description: The saving session event entity to join (e.g. event.octopus_energy_{{ACCOUNT_ID}}_octoplus_saving_session_events)
      selector:
        entity:
          filter:
          - domain:
            - event
            integration: octopus_energy
          multiple: false
  source_url: https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/blueprints/octopus_energy_octoplus_join_saving_session.yml
mode: single
variables:
  saving_session_event_entity: !input saving_session_event_entity
trigger:
- platform: state
  entity_id: !input saving_session_event_entity
condition:
- condition: template
  value_template: "{{ state_attr(saving_session_event_entity, 'available_events') | length > 0 }}"
action:
- variables:
    first_event: "{{ state_attr(saving_session_event_entity, 'available_events')[0] }}"
- service: octopus_energy.join_octoplus_saving_session_event
  data:
    event_code: "{{ first_event['event_code'] }}"
  target:
    entity_id: !input saving_session_event_entity
- service: persistent_notification.create
  data:
    title: Joined Saving Sessions
    message: >
      A new Octopus Energy saving session has been joined. It starts at {{ first_event['event_start'].strftime('%H:%M') }} on {{ first_event['event_start'].day }}/{{ first_event['event_start'].month }}
